name: Release

on:
  release:
    types: [published]

jobs:
  release_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install project dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Release package
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload package
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release upload ${{ github.event.release.tag_name }} dist/*.tar.gz  dist/*.whl --clobber
        if: ( github.event_name == 'release' && github.event.action == 'published' )
